### ISSUE TITLE
Take actual correlation values of gene pairs

### ISSUE THREAD

**Issue by dpolychr** [andymckenzie/DGCA#1]
Hi Andy and many thanks for your useful package. 
I have a gene pairs dataframe (mydf):

Psma4	Mcpr1
9430016H08Rik	1110034B05Rik
LOC433494	Itgb4bp
4933427E11Rik	Jrk
Mfhas1	LOC434299
LOC436084	Eef1a1
LOC434064	Gm461

I can very easily plot the correlation of expression values between condition A and B for the first gene pair for example:

plotCors(inputMat = mydf, design = design_mat, compare = c("conditionA", "conditionB"), geneA = "Psma4", geneB = "Mcpr1")

but i was wondering whether there is any function implemented in your package that could give me the actual correlation value for every gene pair in this df.

Thanks,
Dimitris

**Comment by andymckenzie** [comment]
Hi Dimitris, 

Thanks for using the package. 

There's no built-in function for this, but something like the below should work if you want to print out the actual correlation values for these genes pairs. Basically you subset your input matrix for only those gene pairs, perform ddcorAll, and then select the gene pairs that have the correlations which you want to view. 

Btw, you seem to use "mydf" to refer to both the gene pairs as well as the input gene expression matrix, so I'm using it to refer to the latter, and a df gene_pairs to refer to the former. 

```
gene_pairs = data.frame(
  V1 = c("Psma4", "9430016H08Rik", "LOC433494", "4933427E11Rik", "Mfhas1", "LOC436084", "LOC434064"),
  V2 = c("Mcpr1", "1110034B05Rik", "Itgb4bp", "Jrk", "LOC434299", "Eef1a1", "Gm461"))
gene_pairs_genes = unique(unlist(gene_pairs))
mydf_subset = mydf[gene_pairs_genes, ] #subset your gene expression matrix based on the rownames
mydf_subset_ddcor_res = ddcorAll(mydf_subset, design_mat, compare = c("conditionA", "conditionB"),
  nPerm = 0, adjust = "none")

for(i in 1:nrow(gene_pairs)){
  for(j in 1:nrow(mydf_subset_ddcor_res)){
    if(all(gene_pairs[i, ] %in% c(mydf_subset_ddcor_res$Gene1[j], mydf_subset_ddcor_res$Gene2[j]))){
      print(mydf_subset_ddcor_res[j, ])
    }
  }
}
```

**Comment by dpolychr** [comment]
Many thanks Andy for your prompt response!

This part:

for(i in 1:nrow(gene_pairs)){
  for(j in 1:nrow(mydf_subset_ddcor_res)){
    if(all(gene_pairs[i, ] %in% c(mydf_subset_ddcor_res$Gene1[j], mydf_subset_ddcor_res$Gene2[j]))){
      print(mydf_subset_ddcor_res[j, ])
    }
  }
}

seems a bit slow, so I was thinking for a quicker way using dplyr::filter. For example:

filter(mydf_subset_ddcor_res, Gene1 %in% gene_pairs$V1 & Gene2 %in% gene_pairs$V2 )

but the resulting df does not seem to give the correct pairs! Hmmm...

**Comment by dpolychr** [comment]
I found it Andy.

dplyr::inner_join did the trick.

colnames(gene_pairs) = c("Gene1","Gene2")  

dplyr::inner_join(gene_pairs, mydf_subset_ddcor_res)

**Comment by andymckenzie** [comment]
Very cool, Dimitris! Does it make sense to close this issue now?
