### ISSUE TITLE
Running ddcorrAll with nPairs does not result in the same top correlations as running without

### ISSUE THREAD

**Issue by mikaelamo** [andymckenzie/DGCA#10]
Hi,

Great package! Just managed to run into an issue while using it.

Reading the manuals (basic, advanced, and pdf-manual) I find the following information about using nPairs for ddcorrAll:

> To run the full differential correlation analysis and extract all of the top differentially correlated pairs...

and

> nPairs
> Either a number, specifying the number of top differentially correlated identifier pairs to display in the resulting table, or a the string "all" specifying that all of the pairs should be returned. If splitSet is specified, this is reset to the number of non-splitSet identifiers in the input matrix, and therefore will not be evaluated

So it sounds like the ddcorAll should still perform the full analysis, but only return the top nPairs correlations. But when I actually run ddcorAll I get completely different top hits when using nPairs vs not using nPairs, and the analysis runs faster with nPairs specified. This makes it feel like something is wrong and that the parameter simply limits the number of samples analyzed and not the size of the output table.

I don't know if it's a bug or if I have just misunderstood how it's supposed to work and it's actually doing what it's supposed to be doing. Googling this gave me no clarity 😬

Thank you! 😅

**Comment by andymckenzie** [comment]
Hi,

Thank you for using DGCA and for bringing this to my attention. I'm not sure what is happening. From what you're describing, that's not how it's supposed to work. To better diagnose the issue, could you please provide a minimal, reproducible example that includes the dataset and code you are using? This will help me to more accurately investigate the discrepancy you're experiencing.

Best,
Andy

**Comment by mikaelamo** [comment]
Hi,

After a good night of sleep I managed to solve my own issue. I had some NA values for 4 out of my 5500 genes. After removing these rows, running ddcorAll both with and without nPairs gave the same top 100 correlations.

It is still a bit weird to get different nPairs = 100 output with NA values in the df, esp considering the top 100 (and even top 1000+) rows between the NA and non-NA results were identical when running ddcorAll without nPairs, and that the input data was the same for the nPairs = 100 and nPairs = "all" tests. However, since it's not really good practice to include these NA values I don't think it's an issue you should spend too much of your energy trying to look into.

Thank you for your fast response and sorry for wasting your time!

Kind regards,
M
