### ISSUE TITLE
not available for R 4.3

### ISSUE THREAD

**Issue by complexgenome** [andymckenzie/DGCA#16]
Dear developers,
I'm interested to use this package in tandem with megena.

However, when I try to install this package in R 4.3.2 I get error that says this package isn't available for my version of R.
I can't downgrade the R I use; further with R downgrading other packages such as megena would be a challenge.

**Comment by andymckenzie** [comment]
Thank you for using DGCA. 

Unfortunately, DGCA is currently not available on CRAN due to a package dependency issue. 

In the meantime, you can install the development version of DGCA from GitHub: https://github.com/andymckenzie/DGCA

I hope that this is helpful and sorry for the inconvenience.
