### ISSUE TITLE
how to use moduleGO?

### ISSUE THREAD

**Issue by complexgenome** [andymckenzie/DGCA#17]
Hi Developers,
I'm interested to use DGCA in tandem with megena. I follow tutorial at https://rpubs.com/grrompala/656670
However, I'm unable to understand what are the inputs.

I've gene symbols in ensembl ids. 
Is moduleGO to be performed module wise (per module in loop)? Or, do I send all the modules?

I used following code but seems it doesn't work:
```

merge_ens_hgnc <- merge(ensTable,as.data.frame(rownames(countData)), by.x="ensembl_gene_id", by.y="rownames(countData)")
module_merge_ens_hgnc<-merge(ensTable,as.data.frame(module_output$id), by.x="ensembl_gene_id", by.y="module_output$id")

moduleGO_res = moduleGO(
  genes = module_merge_ens_hgnc$hgnc_symbol, 
  labels = module_output$module,
  universe = merge_ens_hgnc$hgnc_symbol, 
  HGNC_clean = FALSE, HGNC_switch = TRUE,
  pval_GO_cutoff = 0.05)

```
Can you provide a test data to understand what are inputs in this?

**Comment by complexgenome** [comment]
I have vector with HGNC symbols as genes. I've a vector with module names as labels. The length of both is same.
I use below code:
```

moduleGO_res = moduleGO(  genes = merge_ens_hgnc$hgnc_symbol,   labels = union_modules,
  universe = unique(merge_ens_hgnc$hgnc_symbol),   HGNC_clean = FALSE, HGNC_switch = TRUE,
  pval_GO_cutoff = 0.05)
  
```
When I run the above code, I get warnings/messages as:

> 
> Finding GO enrichments for module #2, which is called c1_4
> 'select()' returned many:1 mapping between keys and columns
> Finding GO enrichments for module #3, which is called c1_5
> 'select()' returned many:1 mapping between keys and columns
> Finding GO enrichments for module #4, which is called c1_6
> 'select()' returned many:1 mapping between keys and columns
> Finding GO enrichments for module #5, which is called c1_7
> 'select()' returned many:1 mapping between keys and columns
> Finding GO enrichments for m
> 

Can you please help?

**Comment by andymckenzie** [comment]
Hi complexgenome,

Thank you for using DGCA. Your second code attempt is on the right track. The warnings about "many:1 mapping" are normal messages from the ID conversion process and won't affect your results.

Here's how moduleGO works:

- genes: Vector of gene symbols, one per gene
- labels: Vector of module assignments, one per gene (must be same length as genes)
- universe: Vector of all possible genes (usually all genes in your dataset)

Here's a minimal example:

```
# First, install required packages if needed
if (!require("GOstats")) BiocManager::install("GOstats")
if (!require("org.Hs.eg.db")) BiocManager::install("org.Hs.eg.db")

# Create sample data - DNA repair and apoptosis genes
genes <- c("BRCA1", "BRCA2", "ATM", "TP53", "RAD51", "PARP1", 
           "BAX", "BCL2", "CASP3", "CASP8", "CASP9", "FAS")

# Assign modules (DNA repair vs apoptosis genes)
module_labels <- c(rep("DNA_Repair", 6), rep("Apoptosis", 6))

# Create universe (all genes plus some related ones)
universe_genes <- c(genes, "MDM2", "CHEK1", "CHEK2", "BAD", "BCL2L1")

# Run GO analysis
moduleGO_result <- moduleGO(
  genes = genes,
  labels = module_labels,
  universe = universe_genes,
  HGNC_clean = TRUE,
  HGNC_switch = TRUE,
  pval_GO_cutoff = 0.05,
  gene_ontology = "BP"  # Using Biological Process ontology
)

# Fix data frame structure for extraction
fix_module <- function(df) {
  # Add Ontology column 
  df$Ontology <- "BP"  
  # Ensure correct column order and names
  df <- df[, c("GOBPID", "Pvalue", "OddsRatio", "ExpCount", "Count", "Size", "Term", "Ontology")]
  # Return as list containing the data frame
  return(list(df))
}

# Apply fix to both modules
moduleGO_result$enrichment_DNA_Repair <- fix_module(moduleGO_result$enrichment_DNA_Repair)
moduleGO_result$enrichment_Apoptosis <- fix_module(moduleGO_result$enrichment_Apoptosis)

# Extract the results into a table
module_summary <- extractModuleGO(moduleGO_result)

# View enriched terms
head(module_summary)

Note that this example includes a fix to the output structure prior to using extractModuleGO (the fix_module function). This is needed because GOstats has updated its output format since DGCA was initially written. I plan to update the package to handle this automatically in a future release. 

```
Here's the result I got: 

> > head(module_summary)
>         GOID                                                    Term Ontology
> 1 GO:0000075                         cell cycle checkpoint signaling       BP
> 2 GO:0000077                         DNA damage checkpoint signaling       BP
> 3 GO:0000723                                    telomere maintenance       BP
> 4 GO:0000724 double-strand break repair via homologous recombination       BP
> 5 GO:0000725                                  recombinational repair       BP
> 6 GO:0000902                                      cell morphogenesis       BP
>   Size   OR_DNA    pVal_DNA pVal_Apoptosis OR_Apoptosis min_pval
> 1    8 13.33333 0.042986425             NA           NA       NA
> 2    8 13.33333 0.042986425             NA           NA       NA
> 3    4      Inf 0.006302521             NA           NA       NA
> 4    6 50.00000 0.005413704             NA           NA       NA
> 5    6 50.00000 0.005413704             NA           NA       NA
> 6    3       NA          NA     0.02941176          Inf       NA
> 

For your workflow:

- Replace genes with your gene symbols (merge_ens_hgnc$hgnc_symbol)
- Replace module_labels with your module assignments (union_modules)
- Use all genes in your dataset as the universe

The example shows full enrichment analysis for DNA repair and apoptosis pathways. When you adapt it for your data, make sure your genes and labels vectors are the same length, with each position representing one gene and its corresponding module.

**Comment by complexgenome** [comment]
@andymckenzie 
Thank you for your response. It helps.

However, I get error at the end as:

> 
> 'select()' returned many:1 mapping between keys and columns
> Error in getGoToEntrezMap_db(p) :
>   genes being tested do not have corresponding GO terms
>   

Below are my packages loaded:

>   
> other attached packages:
>  [1] GO.db_3.18.0         ggplot2_3.5.1        gprofiler2_0.2.3
>  [4] DGCA_1.0.3           org.Hs.eg.db_3.18.0  HGNChelper_0.8.15
>  [7] GOstats_2.68.0       graph_1.80.0         Category_2.68.0
> [10] Matrix_1.6-5         AnnotationDbi_1.64.1 IRanges_2.36.0
> [13] S4Vectors_0.40.2     Biobase_2.62.0       BiocGenerics_0.48.1 
> [16] MEGENA_1.3.7         igraph_2.1.2         doParallel_1.0.17   
> [19] iterators_1.0.14     foreach_1.5.2      
> 

Can you guide further?

**Comment by andymckenzie** [comment]
Hello, that is not a problem with DGCA, it is one of the other packages, unfortunately I do not know what the problem is there but I hope you are able to find the solution.
