### ISSUE TITLE
Error in moduleDc

### ISSUE THREAD

**Issue by rachitayadav** [andymckenzie/DGCA#2]
Hi Andy, 

I am trying to compare the expression of modules generated by WGCNA between two genotypes. 

I am facing an error in moduleDC: 
```
moduleDC_res = moduleDC(inputMat = data.frame(t(vstTissue)), design = dmat, compare = c("WT_DEL", "DEL"), genes = modules$values, labels = modules$ind, nPerm = 1, number_DC_genes = 3,dCorAvgMethod = "median")
Calculating MDC for module #1, which is called Module_23
Calculating permutation number 1.
Classifying the differential correlation calls.
Calculating the differential correlation average.
Error in matrixStats::colMedians(zdiff_perm_gene_nonself) : 
  Argument 'dim' must be an integer vector of length two.
```
I checked the structures of different objects. Do you have insight into the issue. 

Thanks in advance.

**Comment by andymckenzie** [comment]
Hi and thanks for using DGCA!

Could you please post a small data set to go along with this code that reproduces the potential bug? Otherwise, it is hard for me to tell what the problem might be and help you debug it.

**Comment by rachitayadav** [comment]
Hi Andy, 

I have attached a zip of a Rdata file for the test. Here is the piece of code I used: 
```
modules = stack(module_genes)
modules$ind = as.character(modules$ind)
str(modules)
moduleDC_res = moduleDC(inputMat = vst_temp, design = dmat, compare = c("WT_DEL", "DEL"), genes = modules$values, labels = modules$ind, nPerm = 1, number_DC_genes = 3,dCorAvgMethod = "median")
```

module_genes == Is a list of genes from one module generated using  WGCNS
vst_temp== Expression of genes in that module used for generation of modules (SVA corrected counts)
dmat= design matrix for the 22 samples 
Also, attaching the sessionInfo()

Let me know if you need more information. 
[output.txt](https://github.com/andymckenzie/DGCA/files/3875460/output.txt)

[test.RData.zip](https://github.com/andymckenzie/DGCA/files/3875409/test.RData.zip)

**Comment by rachitayadav** [comment]
Hey Andy, any updates about this error?

**Comment by andymckenzie** [comment]
Hello Rachita, 

I have been able to test your code. I believe the reason that you are getting the 

>   Argument 'dim' must be an integer vector of length two.

error is because nPerms is set to 1. It needs to be set to greater than 1 in order to calculate an average. The default is 50. 

```
library(DGCA)
setwd("")
load("test")
modules$ind = as.character(modules$ind)
moduleDC_res = moduleDC(inputMat = vst_temp, design = dmat, compare = c("WT_DEL", "DEL"), genes = modules$values, labels = modules$ind, nPerms = 50, number_DC_genes = 3, dCorAvgMethod = "mean")
```

Thank you for pointing out this error and for giving a reproducible example. This will be added to the documentation in a future version of DGCA to prevent this error in the future. 

The result has NAs for the modules other than Module_23, but I believe that is because of the way you subsetted the test data. 

Does this solve the problem?

**Comment by rachitayadav** [comment]
Thanks, Andy. It does solve the problem. I was trying to test using a lower permutation count.
