### ISSUE TITLE
Issue with permutation test setting for ddcorAll

### ISSUE THREAD

**Issue by serenity1901** [andymckenzie/DGCA#3]
I am having an issue at the moment running a large number of permutations using the ddcorAll. 
Not unexpectedly, running these permutations requires a lot of memory. However, it seems to be prohibitively the case if I attempt to run 1000 permutations, even if I submit this job to our HPC with additional resources. 
Is it possible to run this function on 1000 permutations? Was it never intended to run so many?

Any advice/guidance/tips to make this possible would be very much appreciated. 

Kind regards,
Sarah

**Comment by andymckenzie** [comment]
Hello and thank you for using DGCA. 

Yes, the number of permutations can cause memory requirements to increase dramatically. 

This is discussed in the DGCA manuscript, for example, https://bmcsystbiol.biomedcentral.com/articles/10.1186/s12918-016-0349-1

> For pooled approaches, fewer permutations are needed because information is shared across gene pairs; for example, given a 10,000 gene data set and five permutations, the differential correlation of each actual gene pair is compared to 249,975,000 permuted gene pairs in order to estimate empirical null p-values. However, this vastly increases the memory footprint required for empirical p-value calculation and q-value estimation. Perhaps as a result, some investigators have used only one permutation of the data in such analyses [9]. If these memory constraints limit the number of permutations possible, we suggest that a reasonable approach is to repeat the analysis

A reasonable idea would be to try a lower number of permutations and/or to repeat the analysis. I hope this helps and I wish you the best.

**Comment by serenity1901** [comment]
Many thanks Andy!
