### ISSUE TITLE
Hello, I'm having an issue with ddMEGENA function.

### ISSUE THREAD

**Issue by ashaypatel** [andymckenzie/DGCA#5]
The error I am getting is this:

`####### PFN Calculation commences ########

Error in serial.PFN(sortedEdge = ijw, Ng = N, maxENum = maxENum) : 
  The input PFG has exceeding number of edges.
`

This function works great on all my datasets except one and I do not know why?
I don't know if this is the write place to ask. Im using ddcorAll() results and feeding them
into ddMEGENA(). I don't why this error is happening!

**Comment by ashaypatel** [comment]
Also, I my data set is 20,000+ genes. What is the best way to handle this much information in ddcorAll() and ddMegena(). I have used default parameters with my data set and design matrix. What do you recommend I do? Thanks!

**Comment by andymckenzie** [comment]
Hello and thanks for using DGCA. 

Unfortunately, I am not and I am not able to answer this. This is a MEGENA issue, as you can see if you google the error message "The input PFG has exceeding number of edges.", which can for example be found in the MEGENA code: https://github.com/cran/MEGENA/blob/master/R/PFN_Computation.R. 

As such, it is out of the scope of the DGCA package, which just provides a wrapper function to MEGENA in ddMEGENA(). 

In terms of how to use the package on a data set with many genes, one possibly helpful source is the discussion of the manuscript describing DGCA: https://bmcsystbiol.biomedcentral.com/articles/10.1186/s12918-016-0349-1#Sec18. 

Best of luck with your research.

**Comment by ashaypatel** [comment]
Hello, thank you for answer! I have a question. When you ran ddMEGENA on your ddcorAll() results, did you remove all the ddcorAll results with a q>=0.05 before running ddMEGENA?

Thanks so much!
Ashay

**Comment by BW15061999** [comment]
Hi,
I guess the problem is in the part of **adjust** in the source codes of **ddMEGENA**
`  if (!adjusted) {
    ddcor_res_sig = ddcor_res[ddcor_res$pValDiff < pval_gene_thresh,]
  }
  else {
    ddcor_res_sig = ddcor_res[ddcor_res$pValDiff_adj < pval_gene_thresh,]
  }`

The parameter **adjust** is set TRUE by default in **ddMEGENA**, but the results of **ddcorAll**, with the parameter **adjust** set to None, wouldn't contain pValDiff_adj. As a result return a zero dimension **ddcor_res_sig**
